version: 2.1

jobs:
  format_terraform:
    working_directory: /terraform
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Check Terraform formatting
          command: |
            terraform fmt
  validate_terraform:
    working_directory: /terraform
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Validate Terraform
          command: |
            terraform init -input=false
            terraform validate
  plan_terraform:
    working_directory: /terraform
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Validate Terraform
          command: |
            terraform init -input=false
            terraform plan
  plan_terraform:
    working_directory: /terraform
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Validate Terraform
          command: |
            terraform init -input=false
            terraform apply --auto-approve=true

workflows:
  terraform_workflow:
    jobs:
      - format_terraform
      - validate_terraform
      - plan_terraform:
          requires:
            - validate_terraform
      - hold_apply:
          type: approval
          requires:
            - plan_terraform
      - apply_terraform:
          filters:
            branches:
              only: master
          requires:
            - hold_apply
