version: 2.1

orbs:
  terraform: "circleci/terraform@3.0.1"

jobs:
  format_terraform:
    executor: terraform/default
    working_directory: ~/terraform
    steps:
      - checkout
      - terraform/fmt
  validate_terraform:
    executor: terraform/default
    working_directory: /terraform
    steps:
      - checkout
      - terraform/init
      - terraform/validate
  plan_terraform:
    executor: terraform/default
    working_directory: /terraform
    steps:
      - checkout
      - terraform/init
      - terraform/plan
  apply_terraform:
    executor: terraform/default
    working_directory: /terraform
    steps:
      - checkout
      - terraform/init
      - terraform/apply

workflows:
  terraform_workflow:
    jobs:
      - format_terraform
      - validate_terraform
      - plan_terraform:
          requires:
            - validate_terraform
      - hold_apply:
          type: approval
          requires:
            - plan_terraform
      - apply_terraform:
          filters:
            branches:
              only: master
          requires:
            - hold_apply