version: 2.1
orbs:
  terraform: "circleci/terraform@3.0.1"
workflows:
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
      - terraform/validate:
          checkout: true
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          persist-workspace: true
          requires:
            - terraform/validate
      - hold-apply:
          type: approval
          requires:
            - terraform/plan
      - terraform/apply:
          attach-workspace: true
          filters:
            branches:
              only: master
          requires:
            - hold-apply