version: 2.1

jobs:
  format_terraform:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Check Terraform formatting
          command: |
            terraform -chdir=./terraform fmt
  validate_terraform:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Validate Terraform
          command: |
            terraform -chdir=./terraform init
            terraform -chdir=./terraform validate
  plan_terraform:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Plan Terraform
          command: |
            terraform -chdir=./terraform init
            terraform -chdir=./terraform plan
  apply_terraform:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Apply Terraform
          command: |
            terraform -chdir=./terraform init
            terraform -chdir=./terraform apply --auto-approve=true

workflows:
  terraform_workflow:
    jobs:
      - format_terraform
      - validate_terraform
      - plan_terraform:
          requires:
            - validate_terraform
      - hold_apply:
          type: approval
          requires:
            - plan_terraform
      - apply_terraform:
          filters:
            branches:
              only: master
          requires:
            - hold_apply
